# Generated by Django 5.1 on 2024-10-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_remove_usuario_cedula_alter_usuario_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('agua', 'Agua'), ('luz', 'Luz'), ('gas', 'Gas'), ('telefonia', 'Telefonía'), ('internet', 'Internet')], max_length=50)),
                ('fecha', models.DateField()),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('detalles', models.TextField(blank=True)),
                ('obligaciones', models.TextField(blank=True)),
                ('duracion', models.PositiveIntegerField()),
                ('fecha_plazo', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plazos', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], max_length=10)),
                ('forma_pago', models.CharField(max_length=50)),
                ('confidencialidad', models.BooleanField()),
            ],
        ),
    ]
