# Generated by Django 5.1 on 2024-10-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='forma_pago',
        ),
    ]
