# Generated by Django 5.1 on 2024-10-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_remove_contrato_forma_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='plazos',
        ),
    ]
