# Generated by Django 5.1 on 2024-10-10 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_remove_contrato_plazos'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.usuario'),
        ),
    ]
