# Generated by Django 5.1 on 2024-10-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_contrato_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
