# Generated by Django 5.1 on 2024-10-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_alter_contrato_obligaciones_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='pagado',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='confidencialidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='servicio',
            field=models.CharField(max_length=100),
        ),
    ]
