# Generated by Django 5.1 on 2024-10-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_remove_contrato_pagado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='obligaciones',
            field=models.TextField(blank=True),
        ),
    ]
