# Generated by Django 5.1 on 2024-10-11 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_alter_contrato_obligaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_plazo',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='servicio',
            field=models.CharField(choices=[('agua', 'Agua'), ('luz', 'Luz'), ('gas', 'Gas'), ('telefonia', 'Telefonía'), ('internet', 'Internet')], max_length=50),
        ),
        migrations.AlterField(
            model_name='factura',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.contrato'),
        ),
    ]
