# Generated by Django 5.1 on 2024-10-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_remove_contrato_fecha_plazo_alter_contrato_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
