# Generated by Django 5.1 on 2024-10-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_contrato_pagado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ini', models.CharField(max_length=15)),
                ('contraseña', models.CharField(max_length=20)),
            ],
        ),
    ]
